base_url = "https://araaha.me"

title = "Araaha"

compile_sass = true
build_search_index = false
minify_html = true
generate_feeds = true
theme = "apollo"

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_theme = "gruvbox-modified"

[extra]
toc = false
use_cdn = false
favicon = "/icon/favicon.ico"
theme = "dark" # light, dark, auto, toggle

menu = [
    { name = "blog", url = "/blog", weight = 1 },
    { name = "projects", url = "/projects", weight = 2 },
    { name = "about", url = "/about", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/araaha/", icon = "github" },
    { name = "email", url = "mailto:ara.ahady@gmail.com", icon = "email" },
    { name = "linkedin", url = "https://linkedin.com/in/araaha", icon = "linkedin" },
    { name = "rss", url = "/atom.xml", icon = "rss" },
]

custom_css = []
