base_url = "https://araaha.me"

title = "Araaha"

compile_sass = true
build_search_index = false
generate_feed = true
minify_html = true

theme = "apollo"
[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_theme = "gruvbox-modified"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.ico"
theme = "dark" # light, dark, auto, toggle

menu = [
    { name = "blog", url = "/blog", weight = 1 },
    { name = "projects", url = "/projects", weight = 2 },
    { name = "about", url = "/about", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/araaha/", icon = "github" },
    { name = "email", url = "mailto:ara.ahady@gmail.com", icon = "email" },
    { name = "rss", url = "/atom.xml", icon = "rss" },
]

custom_css = []
